kind: ConfigMap
apiVersion: v1
metadata:
  name: codeflare-operator-config
data:
  config.yaml: |
    kuberay:
      rayDashboardOAuthEnabled: false
      ingressDomain: "kind"
      certGeneratorImage: registry.access.redhat.com/ubi9@sha256:770cf07083e1c85ae69c25181a205b7cdef63c11b794c89b3b487d4670b4c328
    appwrapper:
      enabled: true
