package controllers

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	MCADImage       = "quay.io/kpostlet/mcad-controller:release-v1.31.0"
	InstaScaleImage = "quay.io/kpostlet/instascale-controller:v0.0.4"
)
